apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: namespacelab9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: otaacrlab009.azurecr.io/api/api:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
